const EXERCISES = [
  {
    id: '1',
    title: 'Mięśnie brzucha',
    exercises: [
      {
        id: '1.1',
        title: 'Jumping jacks',
        time: 30,
        reps: 0,
        video: 'iSSAk4XCsRA',
      },
      {
        id: '1.2',
        title: 'Abdominal crunches',
        time: 0,
        reps: 16,
        video: '_YVhhXc2pSY',
      },
      {
        id: '1.3',
        title: 'Russian twist',
        time: 0,
        reps: 20,
        video: 'wkD8rjkodUI',
      },
      {
        id: '1.4',
        title: 'Mountain climber',
        time: 0,
        reps: 16,
        video: 'nmwgirgXLYM',
      },
      {
        id: '1.5',
        title: 'Heel touch',
        time: 0,
        reps: 20,
        video: 'fLajmFLpJ_w',
      },
      {
        id: '1.6',
        title: 'Leg raises',
        time: 0,
        reps: 16,
        video: 'JB2oyawG9KI',
      },
      {
        id: '1.7',
        title: 'Plank',
        time: 30,
        reps: 0,
        video: 'pSHjTRCQxIw',
      },
      {
        id: '1.8',
        title: 'V-ups',
        time: 0,
        reps: 12,
        video: 'iP2fjvG0g3w',
      },
      {
        id: '1.9',
        title: 'Plank',
        time: 30,
        reps: 0,
        video: 'pSHjTRCQxIw',
      },
      {
        id: '1.10',
        title: 'Abdominal crunches',
        time: 0,
        reps: 12,
        video: 'Xyd_fa5zoEU',
      },
      {
        id: '1.11',
        title: 'Leg raises',
        time: 0,
        reps: 10,
        video: 'JB2oyawG9KI',
      },
      {
        id: '1.12',
        title: 'Heel touch',
        time: 0,
        reps: 16,
        video: 'fLajmFLpJ_w',
      },
      {
        id: '1.13',
        title: 'Side leg raises',
        time: 0,
        reps: 10,
        video: 'jgh6sGwtTwk',
      },
      {
        id: '1.14',
        title: 'Cobra stretch',
        time: 30,
        reps: 0,
        video: 'JDcdhTuycOI',
      },
      {
        id: '1.15',
        title: 'Spine lumbar twist stretch left',
        time: 30,
        reps: 0,
        video: 'BzYBkAvdCJY',
      },
      {
        id: '1.16',
        title: 'Spine lumbar twist stretch right',
        time: 30,
        reps: 0,
        video: 'BzYBkAvdCJY',
      },
    ],
  },
  {
    id: '2',
    title: 'Klatka piersiowa',
    exercises: [
      {
        id: '2.1',
        title: 'Jumping jacks',
        time: 30,
        reps: 0,
      },
      {
        id: '2.2',
        title: 'Knee push-ups',
        time: 0,
        reps: 12,
      },
      {
        id: '2.3',
        title: 'push-ups',
        time: 0,
        reps: 12,
      },
      {
        id: '2.4',
        title: 'Wide arm push-ups',
        time: 0,
        reps: 16,
      },
      {
        id: '2.5',
        title: 'Hindu push-ups',
        time: 0,
        reps: 10,
      },
      {
        id: '2.5',
        title: 'Staggered push-ups',
        time: 0,
        reps: 12,
      },
      {
        id: '2.6',
        title: 'Push-up & rotation',
        time: 0,
        reps: 10,
      },
      {
        id: '2.7',
        title: 'Knee push-ups',
        time: 0,
        reps: 10,
      },
      {
        id: '2.8',
        title: 'Hindu push-ups',
        time: 0,
        reps: 10,
      },
      {
        id: '2.9',
        title: 'Decline push-ups',
        time: 0,
        reps: 12,
      },
      {
        id: '2.10',
        title: 'Staggered push-ups',
        time: 0,
        reps: 10,
      },
      {
        id: '2.11',
        title: 'Shoulder stretch',
        time: 30,
        reps: 0,
      },
      {
        id: '2.12',
        title: 'Cobra stretch',
        time: 30,
        reps: 0,
      },
      {
        id: '2.13',
        title: 'Chest stretch',
        time: 30,
        reps: 0,
      },
    ],
  },
];

export default EXERCISES;
